version: '3.1'

services:
  webapp:
    image: lucassartori/angular-cli
    container_name: ng_app
    ports:
      - 4200:4200
      - 9000:9000
    volumes:
      - .:/home/ng
    tty: true
    environment:
      NODE_ENV: development
